image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
container_name: workernode{{COUNT}}
restart: always
ports:
  - {{PORT}}:8042
environment:
  SERVICE_PRECONDITION: "namenode:9000 namenode:9870 resourcemanager:8088 {{PRECONDATANODE}}"
env_file:
  - ../hadoop.env